### PR TITLE
Minor changes for Figma Looper

### PR DESCRIPTION
**Pull request by girafic**
- resize and rotate is now from center
- added presets
- option for deleting latest creation
- fix for resizing LINES
- other minor changes
- added examples to README

### CODE REVIEW

**Comment by kuldar** [comment]
Wow, thank you so much for help @girafic! ❤️ These are really cool looking improvements and I'm happy to merge this stuff in! I wonder if maybe replacing the delete icon with an "undo" label would be more descriptive though?

**Comment by kuldar** [comment]
Thanks for the update, there seems to be a small merge conflict in `package-lock.json`, but otherwise I'd love to merge it in asap.

**Comment by girafic** [comment]
@kuldar merge conflict resolved, thx for merging changes 👍

**Comment by kuldar** [comment]
Thank you for the help! ❤️

**Pull request merged**
